AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  vibrant-backend

  Sample SAM Template for vibrant-backend

Globals:
  Function:
    Timeout: 30

Resources:
  AssessmentsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: assessments/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        GetAssessment:
          Type: Api
          Properties:
            Path: /assessments/{key}
            Method: get
        SaveAssessment:
          Type: Api
          Properties:
            Path: /assessments/{key}
            Method: post

Outputs:
  AssessmentsApi:
    Description: 'API Gateway endpoint URL for Prod stage'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/'
